#!/bin/bash


SF1=f48cd800


############rtt data###############

grep -rZ -E "tcp_rtt_estm" /home/mininet//Desktop/withflowtablesexp/4s4htopo/syslog > mptcp_rtt

#for subflow 1

grep -rZ -E "$SF1" mptcp_rtt > rtt_sf1
awk '{print $6, $10}' rtt_sf1 > rtt_sf1_new
sed 's/]//' rtt_sf1_new > rtt_new_111_1
sed 's/.//' rtt_new_111_1 > rtt_new_11
# head -n -5 rtt_new_11 > rtt_new_1
#rm rtt_sf1
rm rtt_sf1_new
rm rtt_new_1



###############cwnd data###############

grep -rZ -E "tcp_out" /home/mininet//Desktop/withflowtablesexp/4s4htopo/syslog > mptcp_cwnd_x1
grep -rZ -E "cwnd" /home/mininet//Desktop/withflowtablesexp/4s4htopo/syslog > mptcp_cwnd_out


rm mptcp_cwnd_x1
#rm mptcp_cwnd_x2

grep -rZ -E "$SF1" mptcp_cwnd_out > cwnd_sf1
#awk '{print $7, $12}' cwnd_sf1 > cwnd_sf1_new
awk '{print $6, $11}' cwnd_sf1 > cwnd_sf1_new
sed 's/]//' cwnd_sf1_new > cwnd_new_11_out
#sed 's/[//' cwnd_sf1_new > cwnd_new_11_out
sed 's/.//' cwnd_new_11_out > cwnd_new_11
head -n -5 cwnd_new_11_out > cwnd_new_1
#rm cwnd_sf1_new
#rm cwnd_sf1
#rm cwnd_new_111
rm cwnd_new_1

##############in_flight data####################

grep -rZ -E "in_flight" /home/mininet//Desktop/withflowtablesexp/4s4htopo/syslog > mptcp_in_flight
rm mptcp_in_flight_1 
# for subflow 1

grep -rZ -E "$SF1" mptcp_in_flight > in_flight_sf1
awk '{print $6, $11}' in_flight_sf1 > in_flight_sf1_new
sed 's/]//' in_flight_sf1_new > in_flight_new_11_1
sed 's/.//' in_flight_new_11_1 > in_flight_new_11
head -n -5 in_flight_new_11 > in_flight_new_1
#rm in_flight_sf1_new
#rm in_flight_sf1
#rm in_flight_new_111
#rm in_flight_new_1


#############ssthresh data################

grep -rZ -E "ssthresh" /home/mininet//Desktop/withflowtablesexp/4s4htopo/syslog > mptcp_ssthresh
rm mptcp_ssthresh_1
# for subflow 1

grep -rZ -E "$SF1" mptcp_ssthresh > ssthresh_sf1
awk '{print $6, $11}' ssthresh_sf1 > ssthresh_sf1_new
sed 's/]//' ssthresh_sf1_new > ssthresh_new_111
sed 's/.//' ssthresh_new_111 > ssthresh_new_11
head -n -5 ssthresh_new_11 > ssthresh_new_1
rm ssthresh_sf1_new
rm ssthresh_sf1
#rm ssthresh_new_111 
rm ssthresh_new_1
 
